### ISSUE TITLE
Planet CRC Unable to Build

### ISSUE THREAD

**Issue by TalisaKnight** [SWG-Source/swg-main#14]
1. I entered the commit in: "build.xml" and "build_planet_crc_string_tables.py".
2. I ran git pull to pull in the updated files.
3. I ran the command: "ant build_planet_crc" according to how it was written in "build.xml".

The following is the chat response that it returned with:

> swg@swg:~/swg-main> cd;cd swg-main;ant build_planet_crc
Buildfile: /home/swg/swg-main/build.xml
>
>compile_tab:
>
>cleanup:
>
>build_planet_crc:
>
>BUILD FAILED
/home/swg/swg-main/build.xml:402: Execute failed: java.io.IOException: Cannot run program "utils/build_planet_crc_string_tables.py" (in directory "/home/swg/swg-main"): error=2, No such file or directory
	at java.base/java.lang.ProcessBuilder.start(ProcessBuilder.java:1128)
	at java.base/java.lang.ProcessBuilder.start(ProcessBuilder.java:1071)
	at java.base/java.lang.Runtime.exec(Runtime.java:592)
	at org.apache.tools.ant.taskdefs.launcher.Java13CommandLauncher.exec(Java13CommandLauncher.java:58)
	at org.apache.tools.ant.taskdefs.Execute.launch(Execute.java:424)
	at org.apache.tools.ant.taskdefs.Execute.execute(Execute.java:438)
	at org.apache.tools.ant.taskdefs.ExecTask.runExecute(ExecTask.java:630)
	at org.apache.tools.ant.taskdefs.ExecTask.runExec(ExecTask.java:669)
	at org.apache.tools.ant.taskdefs.ExecTask.execute(ExecTask.java:497)
	at org.apache.tools.ant.UnknownElement.execute(UnknownElement.java:292)
	at jdk.internal.reflect.GeneratedMethodAccessor6.invoke(Unknown Source)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
	at org.apache.tools.ant.dispatch.DispatchUtils.execute(DispatchUtils.java:99)
	at org.apache.tools.ant.Task.perform(Task.java:350)
	at org.apache.tools.ant.Target.execute(Target.java:449)
	at org.apache.tools.ant.Target.performTasks(Target.java:470)
	at org.apache.tools.ant.Project.executeSortedTargets(Project.java:1391)
	at org.apache.tools.ant.Project.executeTarget(Project.java:1364)
	at org.apache.tools.ant.helper.DefaultExecutor.executeTargets(DefaultExecutor.java:41)
	at org.apache.tools.ant.Project.executeTargets(Project.java:1254)
	at org.apache.tools.ant.Main.runBuild(Main.java:830)
	at org.apache.tools.ant.Main.startAnt(Main.java:223)
	at org.apache.tools.ant.launch.Launcher.run(Launcher.java:284)
	at org.apache.tools.ant.launch.Launcher.main(Launcher.java:101)
Caused by: java.io.IOException: error=2, No such file or directory
	at java.base/java.lang.ProcessImpl.forkAndExec(Native Method)
	at java.base/java.lang.ProcessImpl.<init>(ProcessImpl.java:340)
	at java.base/java.lang.ProcessImpl.start(ProcessImpl.java:271)
	at java.base/java.lang.ProcessBuilder.start(ProcessBuilder.java:1107)
	... 24 more

**Comment by TalisaKnight** [comment]
This was resolved thanks to Elour's feedback. The only other issue is to make sure that the EOL for planet_crc_string_table.txt is LF and not CRLF - I just changed that on my copy and now it will generate the iff as intended.

**Comment by AconiteX** [comment]
Fixed via SWG-Source/dsrc@512756a2
